/**
 * You can list and load the various icons from FontAwesome used
 * in the application. They can then be used with the <Icon /> component,
 * located in /src/components/Icon
 */

import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faTrash,
  faPlus,
  faAngleUp,
  faRightFromBracket,
  faCog,
  faAngleDown,
  faFloppyDisk,
  faPaperPlane,
  faDownload,
  faEdit,
  faRotateLeft,
  faHome,
  faUserGroup,
  faComments,
  faCircleNotch,
  faStar,
  faEnvelope,
  faXmark,
  faTriangleExclamation,
  faCaretUp,
  faCaretDown,
  faReply,
  faOtter,
  faCheck,
} from '@fortawesome/free-solid-svg-icons';

library.add(
  faTrash,
  faPlus,
  faAngleUp,
  faRightFromBracket,
  faCog,
  faRotateLeft,
  faAngleDown,
  faFloppyDisk,
  faPaperPlane,
  faDownload,
  faReply,
  faEdit,
  faHome,
  faUserGroup,
  faComments,
  faCircleNotch,
  faStar,
  faEnvelope,
  faXmark,
  faTriangleExclamation,
  faCaretUp,
  faCaretDown,
  faOtter,
  faCheck,
);