import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faTrash,
  faPlus,
  faAngleUp,
  faAngleDown,
  faFloppyDisk,
  faPaperPlane,
  faDownload,
  faHome,
  faUserGroup,
  faComments,
  faGear,
  faCircleNotch,
  faStar,
  faEnvelope,
  faXmark,
  faTriangleExclamation,
} from '@fortawesome/free-solid-svg-icons';

library.add(
  faTrash, 
  faPlus,
  faAngleUp,
  faAngleDown,
  faFloppyDisk,
  faPaperPlane,
  faDownload,
  faHome,
  faUserGroup,
  faComments,
  faGear,
  faCircleNotch,
  faStar,
  faEnvelope,
  faXmark,
  faTriangleExclamation,
);